### ISSUE TITLE
BoS Off-Duty roles have misplaced/missing spawns.

### ISSUE THREAD

**Issue by mazzinsanity** [JasmineRickards/Wasteland-After-Dark#70]
---- Testmerges: ----
-

---- Reproduction: ----
Selecting the BoS Off-Duty role spawns you outside of the BoS Bunker. I was spawned in Upper Warren (NCR Territory). Not sure if every spawn attempt puts you in a different place.

---- Screenshots: ----
-

---- Additional context: ----
It could be that spawn positions are missing for the BoS Off-Duty role.

**Comment by AllCorruptingWyrm** [comment]
Fixed!
