### ISSUE TITLE
New BoS Bunker missing Paladin and Paladin Marshal rooms.

### ISSUE THREAD

**Issue by mazzinsanity** [JasmineRickards/Wasteland-After-Dark#71]
---- Testmerges: ----
-

---- Reproduction: ----
The BoS Bunker lacks accomodation for Paladins and Paladin Marhsals.

---- Screenshots: ----
-

---- Additional context: ----
The previous iteration of the BoS Bunker had a Paladin Marshal office, as well as Paladin Quarters.

**Comment by AllCorruptingWyrm** [comment]
Paladin Quarters is above the Armory
I can add a Marshal office though.

**Comment by mazzinsanity** [comment]
> Paladin Quarters is above the Armory I can add a Marshal office though.

Are these the Quarters? If so, they seem a little small. Maybe they could be expanded a bit for more intractability and RP potential with, for example, a common lounge room (for only the Paladin cool kids) and individual showers.

![image](https://github.com/JasmineRickards/Wasteland-After-Dark/assets/77054674/efff9bee-1da6-43f8-85e1-709fabaff6ad)
