### ISSUE TITLE
Three misplaced airlocks near Cargo in the BoS Bunker.

### ISSUE THREAD

**Issue by mazzinsanity** [JasmineRickards/Wasteland-After-Dark#72]
---- Testmerges: ----
-

---- Reproduction: ----
-

---- Screenshots: ----

![image](https://github.com/JasmineRickards/Wasteland-After-Dark/assets/77054674/ebb02892-33e7-4888-acdf-32a82c7ec213)

---- Additional context: ----
-

**Comment by AllCorruptingWyrm** [comment]
Fixed!
