### ISSUE TITLE
Bighorn role descriptions incorrectly mention the Great Khans as Bighorn owners

### ISSUE THREAD

**Issue by mazzinsanity** [JasmineRickards/Wasteland-After-Dark#83]
---- Testmerges: ----
-

---- Reproduction: ----
-

---- Screenshots: ----
![image](https://github.com/JasmineRickards/Wasteland-After-Dark/assets/77054674/5864ac25-5bce-41dc-a24e-2b6f96dd1ae5)

---- Additional context: ----
To be more in line with server lore (and to avoid potential player confusion) the references made to the Great Khans in Bighorn role descriptions should be changed to the Brotherhood of Steel. Maybe add a part about the harsh punishments Midwestern BoS dishes out to anyone that questions their rule? Additionally, a larger overhaul of Bighorn content to include more references to the BoS could be a good change.

**Comment by iMoeMoe** [comment]
-1

I hate the BoS and if that's the case what's the point of town authorities? Just lap dogs?
